services:
  app:
    build:
      context: .
    depends_on:
      - tailscale-sidecar
    network_mode: service:tailscale-sidecar
    restart: unless-stopped

  tailscale-sidecar:
    image: tailscale/tailscale:latest
    hostname: ${USER}-tailscale-sidecar
    environment:
      TS_AUTHKEY: "${TAILSCALE_ACCESS_KEY}"
      TS_STATE_DIR: "/var/lib/tailscale"
      TS_USERSPACE: "false"
      TS_SERVE_CONFIG: "/config/serve.json"
    ports:
      - "3000:3000"
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./volumes/tailscale:/var/lib/tailscale
      - ./serve.json:/config/serve.json
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
